---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMWorkloadIdentityPoolProvider
metadata:
  name: github-oidc
  namespace: management-system
spec:
  projectRef:
    external: "projects/kubecon-mgmt"
  location: "global"
  workloadIdentityPoolRef:
    name: "github-oidc"
  attributeMapping:
    google.subject: assertion.sub
    attribute.actor: assertion.actor
    attribute.aud: attribute.aud
    attribute.repository: assertion.repository
  oidc:
    issuerUri: "https://token.actions.githubusercontent.com"

The target service indicated by the "audience" parameters is invalid
