---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: cluster-03
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: anz-next-demo-23
spec:
  enableAutopilot: true
  location: us-east1
  releaseChannel:
    channel: RAPID
  workloadIdentityConfig:
    workloadPool: anz-next-demo-23.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: cluster-03
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: anz-next-demo-23
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one. To use it, replace ${PROJECT_ID?} with your project ID.
    issuer: https://container.googleapis.com/v1/projects/anz-next-demo-23/locations/us-east1/clusters/cluster-03
  endpoint:
    gkeCluster:
      resourceRef:
        name: cluster-03
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: cluster-03
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: anz-next-demo-23
spec:
  location: global
  # The resourceID must be "multiclusteringress" if you want to use multi-cluster
  # ingress feature.
  resourceID: multiclusteringress
  spec:
    multiclusteringress:
      configMembershipRef:
        name: cluster-03
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cluster-03
  namespace: flux-system
spec:
  summary: "cluster-03"
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: 'cluster-03'
    namespace: flux-system
  providerRef:
    name: flux-system-dispatch
  eventMetadata:
    project: "anz-next-demo-23"
    cluster: "cluster-03"
    location: "us-east1"
