---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: cluster-01
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: kubecon-mgmt
spec:
  enableAutopilot: true
  location: us-west1
  releaseChannel:
    channel: RAPID
  workloadIdentityConfig:
    workloadPool: kubecon-mgmt.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: cluster-01
  namespace: management-system
  annotations:
    cnrm.cloud.google.com/project-id: kubecon-mgmt
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one. To use it, replace ${PROJECT_ID?} with your project ID.
    issuer: https://container.googleapis.com/v1/projects/kubecon-mgmt/locations/us-west1/clusters/cluster-01
  endpoint:
    gkeCluster:
      resourceRef:
        name: cluster-01
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cluster-01
  namespace: flux-system
spec:
  summary: "cluster-01"
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: '*'
    namespace: flux-system
  providerRef:
    name: flux-system-dispatch
  eventMetadata:
    project: "kubecon-mgmt"
    cluster: "cluster-01"
    location: "us-west1"
