---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant-alpha
  namespace: team-alpha-tenant
spec:
  serviceAccountName: team-alpha
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: tenants
    namespace: flux-system
  prune: true
  wait: false
  path: ./apps/overlays/cluster-01
