apiVersion: v1
data:
    token: ENC[AES256_GCM,data:MjsGs3gmFqAcIqgHTQwmOUqYNyoEfbTWyrW9jcUom+8vT2UAeOaVhdfjpOzqkM2+Wg/FmwHaRJs=,iv:1UWWW1fo7xl/3zrC75F6HydLf7YS7zEyjtD5K5V92nA=,tag:Bg0jW4s41rqxcxHgxP+dHw==,type:str]
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/kubecon-mgmt/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2023-07-20T12:25:29Z"
          enc: CiQA4yHcyWUw5oxUE7qsBu3SvGSz68xjrOAxUks4m8fhZTTkeLMSSQAG8wEzBsl15Go/2RsKDNnMKVEaSFsfM/LEwM9Bs1FbdEH05DJfC6aGI3kR9GaWLqk903kSpLuKdsLwDJHB110TR1KzIEe6aEA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-20T12:25:30Z"
    mac: ENC[AES256_GCM,data:J9WiQm1GvA+dVD+GFNpbDbuH8NkR3bFMiPdTQAKzdn7zWPu0xZPfFcvebI27/Nc1bExc03RNzQCwRn66km94Ejw3rKQmy30eXGhpTvPoBQYHmCH7c+T1453OGevEcGHg/pcbRMGAWrxjkAbwZYbEwrk+DMP1jofwzW331qvopPY=,iv:YTCRaCCY1y6BqzPwQAOYgL2u5ldHT/0htUIO6Um4t3o=,tag:p7EpLaurX8KsCakd4q2ALQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
